---
- hosts: firewall
  gather_facts: yes
  become: yes
  tasks:
  - name: stop firewalld
    service:
      name: firewalld
      state: stopped
      enabled: no

  - name: iptables flush filter
    iptables:
      chain: "{{ item }}"
      flush: yes
    with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

  - name: iptables flush nat
    iptables:
      table: nat
      chain: '{{ item }}'
      flush: yes
    with_items: [ 'INPUT', 'OUTPUT', 'PREROUTING', 'POSTROUTING' ]

  - name: Allow IN on localhost
    iptables:
      chain: INPUT
      source: 127.0.0.1/32
      jump: ACCEPT

  - name: Allow OUT on localhost
    iptables:
      chain: OUTPUT
      source: 127.0.0.1/32
      jump: ACCEPT

  - name: Enable masquerade
    iptables:
      table: nat
      chain: POSTROUTING
      out_interface: enp0s3
      jump: MASQUERADE

  - name: Enable Incomming Connection Tracking
    iptables:
      chain: INPUT
      ctstate: [ 'ESTABLISHED', 'RELATED']
      match: conntrack
      jump: ACCEPT

  - name: Enable Outgoing Connection Tracking
    iptables:
      chain: OUTPUT
      ctstate: [ 'ESTABLISHED']
      match: conntrack
      jump: ACCEPT
  
  - name: Allow traffic from ansible to firewall
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "22"
      jump: ACCEPT
      source: 10.0.0.20/32
      destination: 10.0.0.1/32

  - name: Allow traffic from node1 to firewall
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "22"
      jump: ACCEPT
      source: 10.0.0.10/32
      destination: 10.0.0.1/32

  - name: Allow traffic from node2 to firewall
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "22"
      jump: ACCEPT
      source: 10.0.1.10/32
      destination: 10.0.1.1/32
 
  - name: Allow traffic to node1 node2 and ansible from fw
    iptables:
      chain: OUTPUT
      protocol: tcp
      destination_port: "22"
      jump: ACCEPT
      destination: "{{ item }}"
    with_items:
    - "10.0.0.10/32"
    - "127.0.0.1/32"
    - "10.0.0.20/32"
    - "10.0.1.10/32"

#  - name: Allow traffic from firewall to nodes
#    iptables:
#      chain: OUTPUT
#      protocol: tcp
#      destination_port: "22"
#      jump: ACCEPT
#      source: "{{ item }}"
#    with_items:
#    - "10.0.0.1/32"
#    - "10.0.1.1/32"
#    - "127.0.0.1/32"

  - name: Allow traffic from windows host to firewall
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "22"
      jump: ACCEPT
      in_interface: enp0s3      

  - name: Allow Internet and DNS traffic from LAN (TCP)
    iptables:
      chain: FORWARD
      protocol: tcp
      destination_port: "{{item}}"
      jump: ACCEPT
      in_interface: enp0s8
    with_items:
    - "80"
    - "8080"
    - "443"
    - "53"

  - name: Allow Internet and DNS traffic from LAN (UDP)
    iptables:
      chain: FORWARD
      protocol: udp
      destination_port: "{{item}}"
      jump: ACCEPT
      in_interface: enp0s8
    with_items:
    - "53"

  - name: Allow ssh traffic to node2
    iptables:
      chain: FORWARD
      protocol: tcp
      destination_port: "22"
      jump: ACCEPT
      in_interface: enp0s9

  - name: Deny all traffic
    iptables:
      chain: INPUT
      jump: REJECT
      in_interface: "{{ item }}"
    with_items:
    - enp0s8
    - enp0s9

  - name: Deny all traffic
    iptables:
      chain: INPUT
      jump: DROP
      in_interface: "{{ item }}"
    with_items:
    - enp0s3

  - name: Deny all Outgoing traffic
    iptables:
      chain: OUTPUT
      jump: REJECT
    
  - name: Deny all Forwarded traffic
    iptables:
      chain: FORWARD
      jump: REJECT

