---
- hosts: firewall
  gather_facts: yes
  become: yes
  roles:
    - { role: shhirose.firewalld }
  vars:
    shhirose_firewalld:
      targets:
      - target: REJECT
        zone: internal
      - target: REJECT
        zone: dmz
      - target: DROP
        zone: external
  tasks:
  - name: tildeler int til lan zone
    firewalld:
      zone: internal
      state: enabled
      interface: enp0s8
      permanent: yes
      immediate: yes

  - name: tildeler int til dmz zone
    firewalld:
      zone: dmz
      state: enabled
      interface: enp0s9
      permanent: yes
      immediate: yes
  
  - name: tildeler int til external zone
    firewalld:
      zone: external
      state: enabled
      interface: enp0s3
      permanent: yes
      immediate: yes

  - name: Set masqurade på public int
    firewalld:
      masquerade: yes
      state: enabled
      permanent: yes
      zone: external
      immediate: yes

  - name: tillad port 22 fra ansible maskine til firewall
    firewalld:
      port: 22/tcp
      permanent: yes
      state: enabled
      zone: internal
      immediate: yes
      source: 10.0.0.20/32

  - name: tillad port 22 fra windows host til firewall
    firewalld:
      port: 22/tcp
      permanent: yes
      state: enabled
      zone: external
      immediate: yes
            

  - name: reload firewalld
    service:
      name: firewalld
      state: reloaded
        
